#!/bin/bash

####################
# HELPER VARIABLES #
####################
# Find out where install is located - source directory for everything we need
current_dir=$(pwd)
script_dir=$(dirname $0)
if [ $script_dir = '.' ]; then script_dir="$current_dir"; fi

# Colors
CLEAR='\033[0m'
GREEN='\033[00;32m'
LIGHTGRAY='\033[00;37m'
BLUE='\033[00;34m'
RED='\033[0;31m'

##########
# CHECKS #
##########
if [[ $EUID -ne 0 ]]; then
   printf "${RED}ERROR!${CLEAR} This script must be run as root, try '${BLUE}sudo !!${CLEAR}'\n" 
   exit 1
fi

printf "${BLUE}Launching install from '$script_dir'${CLEAR}"

########################
# INSTALL NEEDED STUFF #
########################
# apt section
needed_packages=(python2.7)

printf "\n\n${BLUE}Checking for required apt packages${CLEAR}\n"
for package in "${needed_packages[@]}"; do
    if [ $(dpkg-query -W -f='${Status}' $package 2>/dev/null | grep -c "ok installed") -eq 0 ]; then
        printf "\n${BLUE}${package} required${CLEAR}\n"
        sudo apt-get install $package
    else
        printf "${LIGHTGRAY}.${CLEAR}"
    fi
done

# pip install section
pip2_packages=(powerline-status)

printf "\n\n${BLUE}Installing things from pip${CLEAR}\n"
for package in "${pip2_packages[@]}"; do
    pip2 -q -q -q install --user ${package}
    printf "${LIGHTGRAY}.${CLEAR}"
done

default_pip_packages=(python-jenkins)

for package in "${default_pip_packages[@]}"; do
    pip -q -q -q install --user ${package}
    printf "${LIGHTGRAY}.${CLEAR}"
done

printf "\n\n${BLUE}Checking for various plugins from git${CLEAR}\n"

# oh-my-zsh
if [ ! -d "$HOME/.oh-my-zsh" ]; then
    sh -c $(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)
    printf "\n${GREEN}oh-my-zsh has been installed${CLEAR}\n"
else
    printf "${LIGHTGRAY}."
fi

# k, better, git-aware version of ls
if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/k" ]; then
        git clone https://github.com/supercrabtree/k $HOME/.oh-my-zsh/custom/plugins/k
        printf "\n${GREEN}k has been installed${CLEAR}\n"
else
    printf "${LIGHTGRAY}.${CLEAR}"
fi

# syntax highlighting
if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting" ]; then
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        printf "\n${GREEN}syntax highlighting has been installed${CLEAR}\n"
else
        printf "${LIGHTGRAY}.${CLEAR}"
fi

#####################################
# COPY ALL .FILES TO HOME DIRECTORY #
#####################################
home_files=(zshrc bash_aliases zsh_aliases vimrc)

for dotfile in "${home_files[@]}"; do
		ln -sf $script_dir/$dotfile ~/.$dotfile
done

printf "\n\n${BLUE}All done!${CLEAR}\n"
