execute pathogen#infect()
colorscheme monokai
filetype plugin indent on
syntax enable
set nocompatible
set smartindent
set ruler
set backspace=2
set tabstop=4
set softtabstop=4
set expandtab
set number
set showcmd
set cursorline
set wildmenu
set lazyredraw
set showmatch
set incsearch
set hlsearch
set rtp+=$HOME/.local/lib/python2.7/site-packages/powerline/bindings/vim/
set whichwrap+=<,>,h,l,[,]
set laststatus=2
set t_Co=256
