scriptencoding utf-8
set encoding=utf-8
colorscheme monokai
syntax enable
set nocompatible
filetype plugin indent on
set smartindent
set ruler
set backspace=2
set tabstop=4
set softtabstop=4
set expandtab
set number
set showcmd
set cursorline
set wildmenu
set lazyredraw
set showmatch
set incsearch
set hlsearch
set whichwrap+=<,>,h,l,[,]
set laststatus=2
set t_Co=256
set mouse=a
set list
set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<
set statusline+=%#warningmsg#
set statusline+=%*
set textwidth=0
